manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/ftc/     # Mouse layers
  projects:
    - name: zmk
      remote: zmkfirmware
      revision: mouse-ftc                   # <--- CHANGE REVISION
      import: app/west.yml
  self:
    path: config